//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackerBridge_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donations()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int DonationID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DonationDate { get; set; }
        public string DonationMessage { get; set; }
        public string DonationStatus { get; set; }
        public string DonationType { get; set; }
        public Nullable<int> CampaignID { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
