//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackerBridge_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
